### ISSUE TITLE
Uncaught Error: spawn EACCES

### ISSUE THREAD

**Issue by ZetaChow** [redefiance/atom-go-rename#4]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.2
**Thrown From**: [go-rename](https://github.com/redefiance/atom-go-rename) package, v0.3.0

### Stack Trace

Uncaught Error: spawn EACCES

```
At child_process.js:1160

Error: spawn EACCES
  at exports._errnoException (util.js:753:11)
  at ChildProcess.spawn (child_process.js:1160:11)
  at Object.exports.spawn (child_process.js:993:9)
  at new BufferedProcess (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:51:37)
  at GoRenameView.module.exports.GoRenameView.confirm (/Users/banmuhuangci/.atom/packages/go-rename/lib/go-rename-view.coffee:62:21)
  at atom-text-editor.<anonymous> (/Users/banmuhuangci/.atom/packages/go-rename/lib/go-rename-view.coffee:17:64)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:246:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:182:20)

```

### Commands

```
     -1:52.4 vim-mode:insert-after (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  4x -1:51.9 core:backspace (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -1:47.1 core:move-right (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  3x -1:46.7 core:backspace (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -1:44.9 core:save (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -1:25.5 core:move-right (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -1:25.2 core:move-left (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -1:24.9 core:move-right (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  2x -1:24.4 core:backspace (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -1:23.3 core:save (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  2x -1:02.6 core:backspace (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -1:00.0 core:save (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  2x -0:41.0 core:undo (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  2x -0:40.0 core:save (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:02.2 core:move-right (atom-text-editor.editor.mini)
     -0:01.9 core:confirm (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {
    "projectHome": "/Users/banmuhuangci/workspace",
    "disabledPackages": [
      "markdown-format"
    ],
    "themes": [
      "seti-ui",
      "atom-dark-syntax"
    ]
  },
  "go-rename": {
    "path": "/Users/banmuhuangci/workspace/go/bin"
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.1.0
autocomplete-css, v0.6.0
autocomplete-html, v0.5.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.6.0
color-picker, v1.6.0
emmet, v2.3.4
go-find-references, v0.1.0
go-plus, v3.3.1
go-rename, v0.3.0
godef, v0.2.1
highlight-line, v0.10.1
highlight-selected, v0.9.1
jsformat, v0.7.18
linter, v0.12.0
linter-golint, v0.2.0
minimap, v4.7.6
minimap-highlight-selected, v4.2.0
pretty-json, v0.3.2
seti-ui, v0.6.3
vim-mode, v0.40.0
web-browser, v1.4.2

# Dev
No dev packages
```

**Comment by zkirill** [comment]
Launch Atom from command line.

**Comment by ZetaChow** [comment]
thank you!!! ^_^
