### ISSUE TITLE
Atom error message on gorename success

### ISSUE THREAD

**Issue by jfesler** [redefiance/atom-go-rename#7]
This error pops up persistently, even if the gorename succeeded:

```
Uncaught Error: Notification must be created with string message: undefined
/Applications/Atom.app/Contents/Resources/app.asar/src/notification.js:25

Hide Stack Trace
Error: Notification must be created with string message: undefined
    at Notification.module.exports.Notification.validate (/Applications/Atom.app/Contents/Resources/app.asar/src/notification.js:25:15)
    at new Notification (/Applications/Atom.app/Contents/Resources/app.asar/src/notification.js:20:12)
    at NotificationManager.module.exports.NotificationManager.addSuccess (/Applications/Atom.app/Contents/Resources/app.asar/src/notification-manager.js:29:35)
    at /Users/jfesler/.atom/packages/go-rename/lib/go-rename-view.coffee:59:30
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:227:18
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

**Comment by dmitris** [comment]
@jfesler - should the issue be closed as well?

**Comment by jfesler** [comment]
Good catch.  This is no over an issue.
