### ISSUE TITLE
Uncaught Error: Notification must be created with string message: undefined

### ISSUE THREAD

**Issue by micahthomas** [redefiance/atom-go-rename#9]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.4.0
**System**: linux 4.3.3-2-ARCH
**Thrown From**: [go-rename](https://github.com/redefiance/atom-go-rename) package, v0.3.0

### Stack Trace

Uncaught Error: Notification must be created with string message: undefined

```
At /usr/share/atom/resources/app.asar/src/notification.js:25

Error: Notification must be created with string message: undefined
    at Notification.module.exports.Notification.validate (/usr/share/atom/resources/app.asar/src/notification.js:25:15)
    at new Notification (/usr/share/atom/resources/app.asar/src/notification.js:20:12)
    at NotificationManager.module.exports.NotificationManager.addSuccess (/usr/share/atom/resources/app.asar/src/notification-manager.js:29:35)
    at /home/micah/.atom/packages/go-rename/lib/go-rename-view.coffee:59:30
    at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:213:47)
    at /usr/share/atom/resources/app.asar/src/buffered-process.js:227:18
    at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

### Commands

```
  3x -1:02.6.0 core:redo (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  2x -0:50.8.0 go-rename:toggle (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:37.7.0 core:move-right (atom-text-editor.editor.mini.is-focused)
     -0:37.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:03.5.0 go-rename:toggle (atom-text-editor.editor.visual-mode.is-focused)
     -0:02.1.0 core:move-right (atom-text-editor.editor.mini.is-focused)
     -0:01.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:01.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "solarized-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-material-ui, v0.8.0
environment, v1.1.1
file-icons, v1.6.13
go-config, v0.3.1
go-plus, v3.5.2
go-rename, v0.3.0
language-docker, v1.1.6
language-protobuf, v0.5.0
last-cursor-position, v0.9.0

# Dev
No dev packages
```

**Comment by spf2** [comment]
when i use gorename from atom using this plugin, it successfully renames, but also shows this alert every time.  i have the latest versions as of right now.

**Comment by javjar** [comment]
Same over here.

However I noticed that selecting: `Rename Identifier` this happens, but selecting `Rename Symbol Under Cursor` works flawlessly showing the message:

> Renamed 4 occurrences in 1 file in 1 package.

Not sure why though, internally both should be using `go-rename`?
